version: '3.7'
services:
  node1:
    image: blockchain:latest
    ports:
    - "3001:3001"
  node2:
    environment:
      - PEERS=ws://node1:6001
    image: blockchain:latest
    ports:
    - "3002:3001"
    links:
      - node1:node1
  node3:
    environment:
      - PEERS=ws://node2:6001
    image: blockchain:latest
    ports:
    - "3003:3001"
    links:
      - node2:node2
